setwd("e://my learning/coursera/r/pract")
power <- read.table("household_power.txt", header=TRUE, sep=";", colClasses = c("character", "character", rep("numeric",7)),na="?")
head(power)
dim(power)
finaldata <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
head(finaldata)
dim(finaldata)
attach(finaldata)
date_time <- paste(Date, Time)
head(date_time)
a <- strptime(date_time, "%d/%m/%Y %H:%M:%S")
head(finaldata)
png(filename = "plot2.png", width = 480, height = 480, units = "px", bg = "transparent")
plot(a, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()

