setwd("e://my learning/coursera/r/pract")
power <- read.table("household_power.txt", header=TRUE, sep=";", colClasses = c("character", "character", rep("numeric",7)),na="?")
head(power)
dim(power)
finaldata <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
head(finaldata)
dim(finaldata)
attach(power)
date_time <- paste(Date, Time)
head(date_time)
finaldata$datetime <- strptime(date_time, "%d/%m/%Y %H:%M:%S")
head(finaldata)
png(filename = "plot1.png", width = 480, height = 480, units = "px")
hist(finaldata$Global_active_power, col = "red", main = "Global Active Power", 
     xlab = "Global Active Power (kilowatts)",breaks = 12, ylim = c(0, 1200))
dev.off()